#!/bin/bash
#
#SBATCH --constraint icelake
#SBATCH --job-name=xs1
#SBATCH --output=jobout.txt
#SBATCH --account=readmsd02
#
#SBATCH --ntasks 72
#SBATCH --nodes 1
#SBATCH --time 10:00
#SBATCH --mem 400GB
#
#SBATCH --get-user-env
#SBATCH --export=NONE
#
unset SLURM_EXPORT_ENV

module purge
module load bluebear
module load matplotlib/3.3.3-foss-2020b
module load iomkl/2020b

export PYBIN="python"
export MAKE_TALYS_DATA="/rds/homes/b/bxp912/apps/python/make_talys_data.py"

export PROC_COUNT=72
export ISOTOPES="/rds/homes/b/bxp912/apps/python/data/isotopes.pz"
export TALYS_BIN="/rds/homes/b/bxp912/apps/talys/bin/talys"

export PROJECTILES="n"
export LOWER_Z=3
export UPPER_Z=92

export LOWER_E=0.01
export UPPER_E=0.20
export INC_E=0.01

$PYBIN $MAKE_TALYS_DATA 0 &   PIDAA=$!
$PYBIN $MAKE_TALYS_DATA 1 &   PIDAB=$!
$PYBIN $MAKE_TALYS_DATA 2 &   PIDAC=$!
$PYBIN $MAKE_TALYS_DATA 3 &   PIDAD=$!
$PYBIN $MAKE_TALYS_DATA 4 &   PIDAE=$!
$PYBIN $MAKE_TALYS_DATA 5 &   PIDAF=$!
$PYBIN $MAKE_TALYS_DATA 6 &   PIDAG=$!
$PYBIN $MAKE_TALYS_DATA 7 &   PIDAH=$!
$PYBIN $MAKE_TALYS_DATA 8 &   PIDAI=$!
$PYBIN $MAKE_TALYS_DATA 9 &   PIDAJ=$!
$PYBIN $MAKE_TALYS_DATA 10 &   PIDAK=$!
$PYBIN $MAKE_TALYS_DATA 11 &   PIDAL=$!
$PYBIN $MAKE_TALYS_DATA 12 &   PIDAM=$!
$PYBIN $MAKE_TALYS_DATA 13 &   PIDAN=$!
$PYBIN $MAKE_TALYS_DATA 14 &   PIDAO=$!
$PYBIN $MAKE_TALYS_DATA 15 &   PIDAP=$!
$PYBIN $MAKE_TALYS_DATA 16 &   PIDAQ=$!
$PYBIN $MAKE_TALYS_DATA 17 &   PIDAR=$!
$PYBIN $MAKE_TALYS_DATA 18 &   PIDAS=$!
$PYBIN $MAKE_TALYS_DATA 19 &   PIDAT=$!
$PYBIN $MAKE_TALYS_DATA 20 &   PIDBA=$!
$PYBIN $MAKE_TALYS_DATA 21 &   PIDBB=$!
$PYBIN $MAKE_TALYS_DATA 22 &   PIDBC=$!
$PYBIN $MAKE_TALYS_DATA 23 &   PIDBD=$!
$PYBIN $MAKE_TALYS_DATA 24 &   PIDBE=$!
$PYBIN $MAKE_TALYS_DATA 25 &   PIDBF=$!
$PYBIN $MAKE_TALYS_DATA 26 &   PIDBG=$!
$PYBIN $MAKE_TALYS_DATA 27 &   PIDBH=$!
$PYBIN $MAKE_TALYS_DATA 28 &   PIDBI=$!
$PYBIN $MAKE_TALYS_DATA 29 &   PIDBJ=$!
$PYBIN $MAKE_TALYS_DATA 30 &   PIDBK=$!
$PYBIN $MAKE_TALYS_DATA 31 &   PIDBL=$!
$PYBIN $MAKE_TALYS_DATA 32 &   PIDBM=$!
$PYBIN $MAKE_TALYS_DATA 33 &   PIDBN=$!
$PYBIN $MAKE_TALYS_DATA 34 &   PIDBO=$!
$PYBIN $MAKE_TALYS_DATA 35 &   PIDBP=$!
$PYBIN $MAKE_TALYS_DATA 36 &   PIDBQ=$!
$PYBIN $MAKE_TALYS_DATA 37 &   PIDBR=$!
$PYBIN $MAKE_TALYS_DATA 38 &   PIDBS=$!
$PYBIN $MAKE_TALYS_DATA 39 &   PIDBT=$!
$PYBIN $MAKE_TALYS_DATA 40 &   PIDCA=$!
$PYBIN $MAKE_TALYS_DATA 41 &   PIDCB=$!
$PYBIN $MAKE_TALYS_DATA 42 &   PIDCC=$!
$PYBIN $MAKE_TALYS_DATA 43 &   PIDCD=$!
$PYBIN $MAKE_TALYS_DATA 44 &   PIDCE=$!
$PYBIN $MAKE_TALYS_DATA 45 &   PIDCF=$!
$PYBIN $MAKE_TALYS_DATA 46 &   PIDCG=$!
$PYBIN $MAKE_TALYS_DATA 47 &   PIDCH=$!
$PYBIN $MAKE_TALYS_DATA 48 &   PIDCI=$!
$PYBIN $MAKE_TALYS_DATA 49 &   PIDCJ=$!
$PYBIN $MAKE_TALYS_DATA 50 &   PIDCK=$!
$PYBIN $MAKE_TALYS_DATA 51 &   PIDCL=$!
$PYBIN $MAKE_TALYS_DATA 52 &   PIDCM=$!
$PYBIN $MAKE_TALYS_DATA 53 &   PIDCN=$!
$PYBIN $MAKE_TALYS_DATA 54 &   PIDCO=$!
$PYBIN $MAKE_TALYS_DATA 55 &   PIDCP=$!
$PYBIN $MAKE_TALYS_DATA 56 &   PIDCQ=$!
$PYBIN $MAKE_TALYS_DATA 57 &   PIDCR=$!
$PYBIN $MAKE_TALYS_DATA 58 &   PIDCS=$!
$PYBIN $MAKE_TALYS_DATA 59 &   PIDCT=$!
$PYBIN $MAKE_TALYS_DATA 60 &   PIDDA=$!
$PYBIN $MAKE_TALYS_DATA 61 &   PIDDB=$!
$PYBIN $MAKE_TALYS_DATA 62 &   PIDDC=$!
$PYBIN $MAKE_TALYS_DATA 63 &   PIDDD=$!
$PYBIN $MAKE_TALYS_DATA 64 &   PIDDE=$!
$PYBIN $MAKE_TALYS_DATA 65 &   PIDDF=$!
$PYBIN $MAKE_TALYS_DATA 66 &   PIDDG=$!
$PYBIN $MAKE_TALYS_DATA 67 &   PIDDH=$!
$PYBIN $MAKE_TALYS_DATA 68 &   PIDDI=$!
$PYBIN $MAKE_TALYS_DATA 69 &   PIDDJ=$!
$PYBIN $MAKE_TALYS_DATA 70 &   PIDDK=$!
$PYBIN $MAKE_TALYS_DATA 71 &   PIDDL=$!
wait
